# Generated by Django 3.0.2 on 2020-04-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DareYou', '0002_auto_20200419_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionsSerializerModel',
        ),
    ]
