# Generated by Django 3.0.2 on 2020-04-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DareYou', '0003_auto_20200419_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
