# Generated by Django 3.0.2 on 2020-04-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DareYou', '0004_auto_20200419_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='DareShared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=100)),
                ('ques_selected_str', models.CharField(max_length=100)),
            ],
        ),
    ]
