# Generated by Django 3.0.2 on 2020-05-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DareYou', '0005_dareshared'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnfBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=100)),
                ('quest_selected_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_of_cnf_box', models.CharField(max_length=250)),
                ('cnf_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfessionBox.CnfBox')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfessionBox.User')),
            ],
        ),
        migrations.AddField(
            model_name='cnfbox',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfessionBox.User'),
        ),
        migrations.CreateModel(
            name='AnsOfCnfBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=50)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DareYou.Question')),
                ('result_of_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfessionBox.Result')),
            ],
        ),
    ]
